<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Услуги");
$APPLICATION->SetPageProperty("tags", "Услуги");
$APPLICATION->SetPageProperty("keywords", "Ключевые, слова, вашего, сайта");
$APPLICATION->SetPageProperty("description", "Описание вашего сайта");
?>
	<div class="projects">
		<?$APPLICATION->IncludeComponent(
			"bitrix:catalog",
			"portfolio",
			array(
				"COMPONENT_TEMPLATE" => "portfolio",
				"IBLOCK_TYPE" => "portfolio",
				"IBLOCK_ID" => "2",
				"TEMPLATE_THEME" => "blue",
				"MESS_BTN_BUY" => "Купить",
				"MESS_BTN_ADD_TO_BASKET" => "В корзину",
				"MESS_BTN_COMPARE" => "Сравнение",
				"MESS_BTN_DETAIL" => "Подробнее",
				"MESS_NOT_AVAILABLE" => "Нет в наличии",
				"DETAIL_USE_VOTE_RATING" => "N",
				"DETAIL_USE_COMMENTS" => "N",
				"DETAIL_BRAND_USE" => "N",
				"SIDEBAR_SECTION_SHOW" => "Y",
				"SIDEBAR_DETAIL_SHOW" => "Y",
				"SIDEBAR_PATH" => "",
				"SEF_MODE" => "Y",
				"AJAX_MODE" => "N",
				"AJAX_OPTION_JUMP" => "N",
				"AJAX_OPTION_STYLE" => "Y",
				"AJAX_OPTION_HISTORY" => "N",
				"AJAX_OPTION_ADDITIONAL" => "",
				"CACHE_TYPE" => "A",
				"CACHE_TIME" => "36000000",
				"CACHE_FILTER" => "N",
				"CACHE_GROUPS" => "Y",
				"USE_MAIN_ELEMENT_SECTION" => "N",
				"SET_LAST_MODIFIED" => "N",
				"SET_TITLE" => "Y",
				"ADD_SECTIONS_CHAIN" => "Y",
				"ADD_ELEMENT_CHAIN" => "N",
				"USE_ELEMENT_COUNTER" => "Y",
				"USE_FILTER" => "N",
				"FILTER_VIEW_MODE" => "VERTICAL",
				"ACTION_VARIABLE" => "action",
				"PRODUCT_ID_VARIABLE" => "id",
				"USE_COMPARE" => "N",
				"PRICE_CODE" => array(
				),
				"USE_PRICE_COUNT" => "N",
				"SHOW_PRICE_COUNT" => "1",
				"PRICE_VAT_INCLUDE" => "Y",
				"PRICE_VAT_SHOW_VALUE" => "N",
				"BASKET_URL" => "/personal/basket.php",
				"USE_PRODUCT_QUANTITY" => "N",
				"PRODUCT_QUANTITY_VARIABLE" => "",
				"ADD_PROPERTIES_TO_BASKET" => "Y",
				"PRODUCT_PROPS_VARIABLE" => "prop",
				"PARTIAL_PRODUCT_PROPERTIES" => "N",
				"PRODUCT_PROPERTIES" => array(
				),
				"SHOW_TOP_ELEMENTS" => "N",
				"TOP_ELEMENT_COUNT" => "9",
				"TOP_LINE_ELEMENT_COUNT" => "3",
				"TOP_ELEMENT_SORT_FIELD" => "sort",
				"TOP_ELEMENT_SORT_ORDER" => "asc",
				"TOP_ELEMENT_SORT_FIELD2" => "id",
				"TOP_ELEMENT_SORT_ORDER2" => "desc",
				"TOP_PROPERTY_CODE" => array(
					0 => "",
					1 => "",
				),
				"TOP_VIEW_MODE" => "SECTION",
				"SECTION_COUNT_ELEMENTS" => "N",
				"SECTION_TOP_DEPTH" => "2",
				"SECTIONS_VIEW_MODE" => "TILE",
				"SECTIONS_SHOW_PARENT_NAME" => "Y",
				"PAGE_ELEMENT_COUNT" => "0",
				"LINE_ELEMENT_COUNT" => "0",
				"ELEMENT_SORT_FIELD" => "sort",
				"ELEMENT_SORT_ORDER" => "asc",
				"ELEMENT_SORT_FIELD2" => "id",
				"ELEMENT_SORT_ORDER2" => "desc",
				"LIST_PROPERTY_CODE" => array(
					0 => "",
					1 => "",
				),
				"INCLUDE_SUBSECTIONS" => "Y",
				"LIST_META_KEYWORDS" => "-",
				"LIST_META_DESCRIPTION" => "-",
				"LIST_BROWSER_TITLE" => "-",
				"DETAIL_PROPERTY_CODE" => array(
					0 => "",
					1 => "",
				),
				"DETAIL_META_KEYWORDS" => "-",
				"DETAIL_META_DESCRIPTION" => "-",
				"DETAIL_BROWSER_TITLE" => "-",
				"DETAIL_SET_CANONICAL_URL" => "N",
				"SECTION_ID_VARIABLE" => "SECTION_ID",
				"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
				"SHOW_DEACTIVATED" => "N",
				"DETAIL_DISPLAY_NAME" => "Y",
				"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
				"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
				"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
				"LINK_IBLOCK_TYPE" => "",
				"LINK_IBLOCK_ID" => "",
				"LINK_PROPERTY_SID" => "",
				"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
				"USE_STORE" => "N",
				"PAGER_TEMPLATE" => ".default",
				"DISPLAY_TOP_PAGER" => "N",
				"DISPLAY_BOTTOM_PAGER" => "Y",
				"PAGER_TITLE" => "Товары",
				"PAGER_SHOW_ALWAYS" => "N",
				"PAGER_DESC_NUMBERING" => "N",
				"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
				"PAGER_SHOW_ALL" => "N",
				"PAGER_BASE_LINK_ENABLE" => "N",
				"SET_STATUS_404" => "N",
				"SHOW_404" => "N",
				"MESSAGE_404" => "",
				"ADD_PICT_PROP" => "-",
				"LABEL_PROP" => "-",
				"SEF_FOLDER" => SITE_DIR."projects/",
				"SECTIONS_HIDE_SECTION_NAME" => "N",
				"SEF_URL_TEMPLATES" => array(
					"sections" => "",
					"section" => "/#SECTION_CODE#/",
					"element" => "#SECTION_CODE#/#ELEMENT_ID#/",
					"compare" => "compare.php?action=#ACTION_CODE#",
					"smart_filter" => "#SECTION_ID#/filter/#SMART_FILTER_PATH#/apply/",
				),
				"VARIABLE_ALIASES" => array(
					"compare" => array(
						"ACTION_CODE" => "action",
					),
				)
			),
			false
		);?>
	</div>
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"services", 
	array(
		"COMPONENT_TEMPLATE" => "services",
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "5",
		"NEWS_COUNT" => "6",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => SITE_DIR."services/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"USE_SHARE" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "NAME",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_TEXT",
			3 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "services_navigation",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Услуги",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>